### ISSUE TITLE
Add sub path

### ISSUE THREAD

**Issue by JGlueck-WIKA** [benkaiser/open-in-azure-devops#6]
It would be great if it would be possible to define a sub path in the configuration.
For instance when I have a repository containing a certain folder where most of my relevant files are located, I'd use that particular sub folder as my workspace root in VSC. If I use the extension, it will always try to find the file under the original base path.

**Comment by benkaiser** [comment]
@JGlueck-WIKA I'm open to accepting PRs, but I'm not longer actively working on this extension

**Comment by sharmaankit1** [comment]
Hi @benkaiser , I tried creating https://github.com/benkaiser/open-in-azure-devops/pull/7 for this issue. Could you please take a look? Thanks.

**Comment by benkaiser** [comment]
Merged change. Now to remember how to republish the extension...

**Comment by benkaiser** [comment]
@sharmaankit1 I was unable to update the extension (it seems they have modified the process since last time, and it is not possible for me to update it under the old account).

Please either publish yourself from this repo following the guide: https://code.visualstudio.com/api/working-with-extensions/publishing-extension

**Comment by sharmaankit1** [comment]
@benkaiser I was able to publish the extension, but had to update the id and the publisher. Here's the new extension link: https://marketplace.visualstudio.com/items?itemName=AnkitSharma.open-in-azure-devops-v2

**Comment by benkaiser** [comment]
Great job, thanks @sharmaankit1
